// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUPOoq5IMQYxIM1X0D0gvaDpSfc8Wi7yY',
    appId: '1:868247640888:web:53068eb0f9329d5b823fcd',
    messagingSenderId: '868247640888',
    projectId: 'smart-parking-272',
    authDomain: 'smart-parking-272.firebaseapp.com',
    storageBucket: 'smart-parking-272.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHYIu0qJmBhwRMm4rNnlbYJlpVjVdibEc',
    appId: '1:868247640888:android:1eae207839dfc5bc823fcd',
    messagingSenderId: '868247640888',
    projectId: 'smart-parking-272',
    storageBucket: 'smart-parking-272.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoeooiwkllBybQ0HwRWMxtC2kps7b0c-c',
    appId: '1:868247640888:ios:a2a7299830c4475a823fcd',
    messagingSenderId: '868247640888',
    projectId: 'smart-parking-272',
    storageBucket: 'smart-parking-272.appspot.com',
    iosBundleId: 'com.example.smartParkingFrontEnd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoeooiwkllBybQ0HwRWMxtC2kps7b0c-c',
    appId: '1:868247640888:ios:f4c6f86aeeb95dd1823fcd',
    messagingSenderId: '868247640888',
    projectId: 'smart-parking-272',
    storageBucket: 'smart-parking-272.appspot.com',
    iosBundleId: 'com.example.smartParkingFrontEnd.RunnerTests',
  );
}
