name: smart_parking_front_end
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  # web_socket_channel: ^2.1.0

  flutter:
    sdk: flutter
  http: "0.13.3" 
  google_maps_flutter: ^2.5.0
  geolocator: ^8.0.1
  permission_handler: ^11.0.1
  flutter_polyline_points: ^1.0.0
  label_marker: ^1.0.1
  stomp_dart_client: 1.0.0
  firebase_core: ^2.23.0
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  firebase_messaging: ^14.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/park.png
    - assets/arrow_icon.png
    - assets/car.png
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
