version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27019:27017"
    volumes:
      - smart-parking-db_mongodb_data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgis:
    image: mdillon/postgis
    container_name: postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: smartparkingdb
      POSTGRES_USER: smartparking
      POSTGRES_PASSWORD: smartparking
    volumes:
      - smart-parking-db_postgis_data:/var/lib/postgresql/data

volumes:
  smart-parking-db_mongodb_data:
  smart-parking-db_postgis_data:
